#baseURL = "http://localhost:8080/"
baseURL = "https://seriousben.com/"
debug = true
verbose = true
title = "Benjamin Boudreau"
copyright = "Copyright © Benjamin Boudreau 2017-2020"
theme = "seriousben"
rssLimit = 100
enableEmoji = true
[author]
  name = "Benjamin Boudreau"

[taxonomies]
  tag = "tags"

[params]
copyright = "Copyright © Benjamin Boudreau 2017-2020"
copyrightUrl = "https://seriousben.com/"
twitter = "seriousben"
github = "seriousben"
linkedin = "boudreaubenjamin"
highlightjs = true

  [[menu.primary]]
    name = "Posts"
    url = "/posts/"
    weight = 10

  [[menu.primary]]
    name = "Curated Links"
    url = "/links/"
    weight = 20
